# Setup
title:               procfs
description:         'Security and Linux'
url:                 https://blog.procfs.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Santosh Ananthakrishnan
  url:               https://twitter.com/santoshankr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
